function handlingChange()
	local modelId = 400
	setModelHandling(modelId, "mass", 20000)
	setModelHandling(modelId, "turnMass", 10000)
	setModelHandling(modelId, "dragCoeff", 0.0)
	setModelHandling(modelId, "centerOfMass", {0.0, 0.0, 0.0} )
	setModelHandling(modelId, "percentSubmerged", 100)
	setModelHandling(modelId, "tractionMultiplier", 1.0)
	setModelHandling(modelId, "tractionLoss", 1.0)
	setModelHandling(modelId, "tractionBias", 0.50)
	setModelHandling(modelId, "numberOfGears", 5)
	setModelHandling(modelId, "maxVelocity", 250)
	setModelHandling(modelId, "engineAcceleration", 15)
	setModelHandling(modelId, "engineInertia", -100.0)
	setModelHandling(modelId, "driveType", "awd")
	setModelHandling(modelId, "engineType", "petrol")
	setModelHandling(modelId, "brakeDeceleration", 5)
	setModelHandling(modelId, "brakeBias", 0.50)
	setModelHandling(modelId, "ABS", true)
	setModelHandling(modelId, "steeringLock", 40)
	setModelHandling(modelId, "suspensionForceLevel", 1.00)
	setModelHandling(modelId, "suspensionDamping", 1.00)
	setModelHandling(modelId, "suspensionHighSpeedDamping", 1.00)
	setModelHandling(modelId, "suspensionUpperLimit", 0.00)
	setModelHandling(modelId, "suspensionLowerLimit", 0.00)
	setModelHandling(modelId, "suspensionFrontRearBias", 0.5)
	setModelHandling(modelId, "suspensionAntiDiveMultiplier", 0.0)
	setModelHandling(modelId, "seatOffsetDistance", 0.00)
	setModelHandling(modelId, "collisionDamageMultiplier", 0.0)
	setModelHandling(modelId, "monetary", 0)
	setModelHandling(modelId, "modelFlags", 0)
	setModelHandling(modelId, "handlingFlags", 0)
	setModelHandling(modelId, "headLight", "long")
	setModelHandling(modelId, "tailLight", "long")
	setModelHandling(modelId, "animGroup", 0)
end
addEventHandler("onResourceStart", resourceRoot, handlingChange)